version: '3'

services:
  db:
    image: postgres:16.1-alpine3.19
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgres/data
    restart: always

